const express=require('express')
const authintication = require('../middlewares/authorization')
const authintications = require('../middlewares/authintication')
const { addLesson,getLesson, updateLesson, deleteLesson, getAllLesson ,completeLesson} = require('../controllers/lesson')
const { getLessonValidator, deleteLessonValidator, updateLessonValidator, addLessonValidator, getAllLessonValidator, completeLessonValidator} = require('../utils/validators/lesson')
const uploadVideo = require('../controllers/videouploader')
const { enrolledCourse } = require('../middlewares/enrolledcourses')
const upload = require('../middlewares/multer')

const router = express.Router()
router.post('/:sectionId/addlesson',authintications,authintication,addLessonValidator,addLesson)
router.get('/getlesson/:lessonId',getLessonValidator,authintications,enrolledCourse,getLesson)
router.get('/:sectionId/getalllesson/',getAllLessonValidator,getAllLesson)
router.delete('/:sectionId/deletelesson/:lessonId',authintications,authintication,deleteLessonValidator,deleteLesson)
router.put('/updatelesson/:lessonId',authintications,authintication,updateLessonValidator,updateLesson)
router.put('/commpletelesson/:lessonId',authintications,completeLessonValidator,completeLesson)
module.exports=router